name: Windows Jekyll Build

on:
  push:
    paths: 
      - Gemfile
      - Gemfile.lock
      - .github/workflows/jekyll_win_build.yml
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1 # v1.161.0
        with:
          ruby-version: '3.2'
          bundler-cache: true
          cache-version: 1
      - name: Setup build dependencies
        run: |
          npm ci
      - name: make caches
        run: |
          mkdir cache
          mkdir cache/resize
      - name: Build with Jekyll
        id: build
        run: npx gulp build
        env: 
          JEKYLL_ENV: production
