# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll site to Pages

on:
  # Runs on pushes targeting the default branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: make caches
        run: |
          mkdir cache
          mkdir cache/resize
      - name: Cache Images
        uses: actions/cache/restore@v3
        with:
          path: cache
          key: cache_test-${{ hashFiles('assets/**') }}
          restore-keys: |
            cache_test
      - name: check cache
        run: |
          ls -l cache
          ls -l cache/resize
      - name: Setup node
        uses: actions/setup-node@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1 # v1.161.0
        with:
          ruby-version: '3.2' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 1 # Increment this number if you need to re-download cached gems
      - name: Setup build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install graphicsmagick
          npm ci
      - name: Checks Ruby Gems
        run: bundle list
      - name: Checks npm packages
        run: npm list
      # - name: Setup Pages
      #   id: pages
      #   uses: actions/configure-pages@v4
      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        id: build
        run: npx gulp build -j '--config _config.yml,_dev_config.yml'
        env:
          JEKYLL_ENV: production
      - name: Check HTML
        uses: chabad360/htmlproofer@master
        with:
          directory: "./_site" #--enforce_https false <-- why doesn't this work?
          arguments: --ignore-status-codes "999,403" --ignore_urls "/kastner.ucsd.edu/,/onlinedigeditions.com/,/e4e.ucsd.edu/,/jaffeweb.ucsd.edu/,/instagram.com/" --assume-extension .html --swap-urls '^https\://e4e.ucsd.edu/:/'
      - name: Checks files
        run: ls -l cache
      - name: Checks files
        run: ls -l assets
      - name: remove extra cache
        if: steps.build.outcome == 'success'
        run: rm -rf cache/resize_temp
      - name: Cache Images
        uses: actions/cache/save@v3
        if: always()
        with:
          path: cache
          # this should not hash every file.... how do we connect this to a new cache?
          key: cache_test-${{ hashFiles('assets/**') }}
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check Files
        run: ls -l .
