# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Build page for deploy to e4e-dev.ucsd.edu

on:
  # Runs on pushes targeting the default branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  id-token: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1 # v1.161.0
        with:
          ruby-version: '3.2' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 1 # Increment this number if you need to re-download cached gems
      - name: Setup build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install graphicsmagick
          npm ci
      - name: Checks Ruby Gems
        run: bundle list
      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        run: npx gulp build #bundle exec jekyll build --baseurl "" --config _config.yml,_e4e_dev_config.yml
        env:
          JEKYLL_ENV: production

